### ISSUE TITLE
carry initial search terms forward?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#828] opened 2015-12-16 22:52 UTC
Suggestion from today's training. Apologies if this has been discussed. I couldn't find it. 

There was a suggestion that the search terms that were entered in the home page search box could be carried forward into the "search again" box, so that users could add terms to their search without having to type them again. 

Of course, this can also be achieved by simply clicking the back button from the grid view. (But Google keeps the term in the box, if that is the gold standard.)

**Comment by redlibrarian** [comment] 2016-03-10 19:09
Duplicate of #756. Closing.

**Closed by redlibrarian** 2016-03-10 19:09 UTC
Labels: enhancement
