### ISSUE TITLE
Tiny ILL link was removed. 

### ISSUE THREAD

**Issue by jhennig** [ualbertalib/discovery#1363] opened 2018-10-30 14:50 UTC
**Describe the bug**
I believe a Tiny "ILL" text was recently removed.  I got a helpdesk ticket from Carolyn about it.

**To Reproduce**
1. Go to https://www.library.ualberta.ca/journals-search
2. do an ejournal search for: FMCG Snapshot 
3. There should be a very tiny "ILL" text that links to erms.  This is no longer there. It may even have been in the footer of the page, (but i can't say for sure) I remember it was near the bottom anyway.
The ILL text is so small it looks like a dot, it was meant to be obscure as it really only provides value to staff.

**Comment by seanluyk** [comment] 2018-10-30 14:56
Interesting, the ILL link does still appear on other journal records, just not this one. I don't fully understand what prompts this to appear or not

**Comment by seanluyk** [comment] 2018-10-30 17:54
I believe this is specified [here](https://github.com/ualbertalib/discovery/blob/87b665ee850f3e41ed35feb6a4eb76b152ae0ab6/app/views/catalog/_sfx_holdings.html.erb) which requires an ISSN to be present in the source data for the link to display. I don't see one in the librarian view (022 $a) so I suspect that the problem is at the source

**Comment by theLinkResolver** [comment] 2018-10-30 20:38
Yikes... this is familiar now. Basing anything on the presence/absence of an ISSN is pretty sketchy! Probably goes without saying but I want to get that on the record.

**Comment by seanluyk** [comment] 2018-10-30 20:47
@theLinkResolver  - I'm not 100% confident that's how this is working, more of a suspicion.

**Comment by pgwillia** [comment] 2018-10-30 20:55
The tiny link to the ILL goes to `https://erms.library.ualberta.ca/coral/terms/?issn=<issn>`. The link doesn't make any sense if there isn't an issn.  Is there a better way?

**Comment by jhennig** [comment] 2018-10-30 21:05
the terms tool can also use ISBN but that's it.
 https://erms.library.ualberta.ca/coral/terms/?isbn=<isbn>

**Comment by theLinkResolver** [comment] 2018-10-30 21:05
Wow, if the Coral lookups depend on ISSNs, what can you do, I guess. This was one advantage of the OUR database as it worked with SFX target names. I don't know enough about Coral to know if that's even a possibility.

**Comment by seanluyk** [comment] 2018-10-30 21:32
I don't think there's really anything we can do if these links depend on standard numbers if there are items that don't use standard numbers in SFX.

**Comment by seanluyk** [comment] 2018-11-01 16:06
Closing as this is not a Discovery issue.

**Closed by seanluyk** 2018-11-01 16:06 UTC
Labels: bug
