### ISSUE TITLE
Ranking of libraries in library facet

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#599] opened 2015-10-07 21:31 UTC
It looks like subjects are ranked in descending order, as are all other facets. Why not rank libraries the same way? It looks like it's currently ranked in alphabetic order, which means most UofA stuff is at the bottom.

**Comment by redlibrarian** [comment] 2015-10-08 15:14
User feedback was that if they were looking for a particular library, it was hard to find if they were sorted by number of items. The UA stuff is at the bottom, but at least a user knows where to look, as opposed to ranking by number of hits which means they will need to read through the whole list to find the library they want to limit by. The problem is that our locations all start with "University of Alberta" (because NEOS). We can look at this again, but it was a common user complaint when we tested before.

**Comment by seanluyk** [comment] 2015-10-08 15:17
I was thinking about that - wouldn't we be at the top anyway given our
relative size to the other NEOS members most of the time anyway?


*Sean Luyk, B.Mus, MA, MLIS*Music Librarian
<http://guides.library.ualberta.ca/music>
Subject Librarian, Anthropology
<http://guides.library.ualberta.ca/anthropology>
Humanities & Social Sciences Library
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta  T6G 2J8
780-492-6779 | https://sites.google.com/a/ualberta.ca/sean-luyk/

**Comment by redlibrarian** [comment] 2015-10-08 15:30
*A* U of A library like Rutherford, perhaps, but not all of them. Our libraries are split out, so for example Coutts or BSJ wouldn't necessarily be at the top, compared to, say, Macewan. A ranking in descending order would have the U of A libraries dispersed among the list.

**Comment by redlibrarian** [comment] 2015-11-03 21:12
@seanluyk Can we close this issue, or should I move it to the January milestone for more discussion. I doubt we'll have time to make any changes to this before the end of November.

**Comment by seanluyk** [comment] 2015-11-09 21:46
Not urgent, so we can move it to the Jan milestone. I think it still warrants some discussion, but it can wait!

**Closed** 2016-09-15 14:41 UTC
Labels: enhancement, For discussion, question
