### ISSUE TITLE
Searching with accented letters issue

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#876] opened 2016-01-14 18:22 UTC
I may have found another glitch in Blacklight. It seems the database treats accented letters differently from non-accented ones. For example, if you search for "editions du ble" you will find 4 titles whereas if you add the accent on the two 'e's, as in "éditions du blé", you will get 170 results. I think it is preferable not to oblige users to include accents. Thank you for sending this along to those still working on Blacklight.

**Comment by redlibrarian** [comment] 2016-01-14 18:30
Duplicate of #866 (both reported by the same user with the same example). Closing.

**Closed** 2016-01-14 19:48 UTC
