### ISSUE TITLE
"data not available" result for SFX journals

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#915] opened 2016-03-03 17:54 UTC
@redlibrarian You explained this issue to us yesterday in the context of a helpdesk ticket, but I am going to log it here, as I keep getting this error, and am wondering if something is bogging down the SFX lookups this week.

![datanotavail](https://cloud.githubusercontent.com/assets/14913579/13503720/4ebfc224-e12e-11e5-84ff-4199855b6501.jpg)

**Comment by theLinkResolver** [comment] 2016-03-10 17:08
I have not been getting this error at all this week. @ualbertalib/discovery-testing Anyone else? Try loading [this record](https://www.library.ualberta.ca/catalog/954921392997) to see if you get the error.

Whatever was ailing the SFX lookups last week seems to have passed. Records are displaying much faster.

**Comment by linds37** [comment] 2016-03-10 20:37
I have not seen this error. The linked record shows up fine.

**Comment by theLinkResolver** [comment] 2016-03-15 15:10
@redlibrarian I'm going to reopen this because I am seeing the error again. Is it because the SFX update is being applied right now? @marcelgee 

https://www.library.ualberta.ca/catalog/1000000000815519

**Comment by theLinkResolver** [comment] 2016-03-16 21:30
Getting the error now
https://www.library.ualberta.ca/catalog/110978977565339

**Comment by redlibrarian** [comment] 2016-03-31 15:09
My sense is that the SFX server is taking longer than it used to to respond. I will raise the timeout limit, which will help (though the pages will appear to be taking longer to load).

**Comment by redlibrarian** [comment] 2016-03-31 20:25
The problem is clearly only intermittent (I'm access all the links in this issue with no problems right now). Notwithstanding, I've raised the timout limit to 4 seconds (same as Symphony), so we should see an improvement.

**Comment by redlibrarian** [comment] 2016-04-05 15:55
I'm going to close this, as 4 seconds seems to be sufficient for now. Feel free to reopen it if the problem persists.

**Comment by theLinkResolver** [comment] 2016-04-12 20:34
@redlibrarian This one has been unavailable all day.
https://www.library.ualberta.ca/catalog/110978979776939

**Comment by redlibrarian** [comment] 2016-04-12 21:19
OK, thanks. I don't know what we can do about this. @sjshores @kgood we should perhaps discuss this and see what our options are.

**Comment by redlibrarian** [comment] 2016-04-19 18:30
We just got a ticket stating that users are hitting the "data not available message" quite frequently. I'm going to take off the timeout for SFX records (we aren't noticing a problem with Symphony records) until we can figure this out.

**Comment by redlibrarian** [comment] 2018-04-30 18:02
Done when:

- [ ] Holdings are populated asynchronously
- [ ] We don't get timeout messages anymore

**Closed by redlibrarian** 2018-04-30 18:02 UTC
Labels: For discussion, bug
