### ISSUE TITLE
"Internet Access" (856) link not appearing.

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#889] opened 2016-01-21 21:01 UTC
https://library.ualberta.ca/catalog/2914678

vs. 

https://www.library.ualberta.ca/catalog/2914678

@redlibrarian The first one was sent to me in a helpdesk ticket (2016012110417) and I noticed that the electronic access link wasn't displaying. Now, I'm not sure why someone would end up copying the URL without the www, but should this work, regardless?

**Comment by theLinkResolver** [comment] 2016-01-21 21:03
@redlibrarian Okay, that's weird. They both work normally when I click the links in the GitHub message. Check the link in the helpdesk ticket I cited, I guess.

**Comment by theLinkResolver** [comment] 2016-01-21 21:06
@redlibrarian Maybe a java error or something? I know weird stuff happens sometimes when clicking links in OTRS (e.g. Get It links fail). I use Firefox, which seems better than Chrome in this regard, but not perfect. Maybe we should just implicate OTRS and close this?

**Comment by redlibrarian** [comment] 2016-01-21 21:19
@theLinkResolver The two links in the ticket are:

https://library.ualberta.ca/catalog/991042728210868

and

https://library.ualberta.ca/catalog/2914678

So, one SFX and one Symphony record. For some reason the "Internet Access" link isn't coming through in the Symphony record, and the user is confused about the links in the SFX record. I can look into why the Internet Access link isn't appearing in the symphony record, but the confusion over the two kinds of records will have to wait until we deduplicate.

**Comment by redlibrarian** [comment] 2016-01-21 21:23
The Symphony record doesn't have a "url_fulltext_display" field, which is necessary for the link to appear. I don't know why that field isn't present - it's based on the two digit code for relationship in the 856.

**Comment by theLinkResolver** [comment] 2016-01-21 21:24
@redlibrarian makes sense to me - you will see that I have copied you on the reply to the ticket.

As for the URL, do you find that it does appear when you do a search for the journal? That's what I'm seeing.

**Comment by redlibrarian** [comment] 2016-01-21 21:32
@theLinkResolver Yes, that worked for me. I'm not sure what's going on here. In any event, the links in the SFX record and the Internet Access link (when it appears) should both be working.

**Comment by redlibrarian** [comment] 2016-03-31 15:03
@theLinkResolver I'm not sure if this is still an outstanding problem?

**Comment by theLinkResolver** [comment] 2016-03-31 19:39
@redlibrarian Sort of... go to this [helpdesk ticket](https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=32474#117246) and click on the link to the "complete record with more information". When I do that, I don't see the U of A access link in the record. But when I search for this journal, the link appears as expected. I just don't get why it's not displaying when I link out of OTRS (and if this might have some other implication for users).

**Comment by redlibrarian** [comment] 2016-03-31 20:05
@theLinkResolver Ah, I think I know why I'm confused. When I link out of OTRS, I *do* see the U of A Access link in the "complete record with more information".

**Comment by theLinkResolver** [comment] 2016-03-31 20:26
@redlibrarian Hmm, same result for Chrome and IE. (I use FF)

**Comment by redlibrarian** [comment] 2016-04-01 21:26
Ah. I managed to replicate the problem on UWS. Investigating.

**Comment by redlibrarian** [comment] 2016-04-01 21:35
Fascinating. When I look at the JS Console on the page that isn't loading the link (coming out of OTRS) I see the message "62914678:1 Blocked script execution in 'https://search.library.ualberta.ca/catalog/2914678' because the document's frame is sandboxed and the 'allow-scripts' permission is not set." This message does not occur when I find the record in the system. When I copy and paste the URL of the page view with the error and paste it into a new tab, the link appears (and the error disappears). I would say that the problem seems to just be when linking out of OTRS for some reason. Randy's message says that he can see the link, so I'd say this is a bug related to very specific conditions. I'm not sure how I'd go about troubleshooting further than that, and I don't know if the effort is worth it right now. I recommend closing the ticket, and opening a new one if we notice a more widespread problem. What do you think, @theLinkResolver ?

**Comment by theLinkResolver** [comment] 2016-04-01 21:42
@redlibrarian That is great that you were able to get some understanding of this bizarre issue. Having logged it here, I agree that we should close this, since we haven't heard any other instances of this happening. That said, this needs to be broadcasted to anyone who handles helpdesk tickets that may contain a link to a Blacklight record. I have an idea of who that is, on my floor, but perhaps @redlibrarian and @sjshores can contemplate who else might need to know about this. And then, between the three of us, we can put together a brief communication for those affected.

**Comment by redlibrarian** [comment] 2016-04-01 21:45
I think we can certainly communicate it to ITS. The problem is intermittent even then, as I didn't see the issue until I was on Chrome/Laptop/UWS. So yes, I think we can close this and just communicate the issue to others (most/all Blacklight tickets should come through me anyway, for now).

**Closed** 2016-05-03 19:22 UTC
Labels: bug
