### ISSUE TITLE
No UofA Access - On-campus access allowed at the following locations

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#600] opened 2015-10-07 21:38 UTC
This is a debatable one rather than an issue necessarily, but it seems a little confusing when viewing an [ebook record where UofA has no access](http://search.library.ualberta.ca/catalog/6440581). 

The note says **Note: No University of Alberta Access. On-campus access allowed at the following locations** and then provides links to records that a UofA user can't access. It's also not clear that all of these locations in fact allow walk -ins.

**Comment by redlibrarian** [comment] 2015-10-08 15:15
This is a bug that keeps coming back. See #538 . I'm going to close this issue, as it's a duplicate of one we already have open.

**Closed by redlibrarian** 2015-10-08 15:15 UTC
Labels: bug, UI
