### ISSUE TITLE
Missing holdings in ebook records / duplicate records?

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#1086] opened 2016-10-16 17:38 UTC
Hi. I'm doing some research today, and have come across several ebook records like this one (look up the title _The SAGE handbook of grounded theory_):

https://www.library.ualberta.ca/catalog/7581011

https://www.library.ualberta.ca/catalog/6914519

They say this in the holdings note:
"Note: No University of Alberta Access. On-campus access allowed at the following locations:
No copies found. This item may be lost or missing, or the data may be temporarily unavailable. Please ask us for assistance."

In every case, there is also at least one record which does give UA holdings, but it's farther down in the list of results - in this case, 5th on the list: https://www.library.ualberta.ca/catalog/7585261

**Comment by theLinkResolver** [comment] 2016-10-17 18:11
Thanks @linds37. I just had a chat with Michael from the E-Books cataloguing team and he filled me in on this specific case, and the general context of the problem. It boils down to an issue with getting deleted records out of the Solr index (#932), but here is the context so we all understand the issue.

The e-book team had to purge a set of records for the SAGE Research Methods package last week, due to an erroneous URL as supplied by SAGE. They reloaded the records the next day (Wednesday). In this case, that is the record you found 5th on the list. The problem is that those purged records, which disappear from Sirsi the day after they are marked for deletion, are not being deleted from the Solr index in a timely fashion. Without some digging, I'm not sure exactly why there are two purged records, but I'm guessing that one is from an even earlier purge (yikes!), maybe even from a different SAGE product/package.

I will add that the purge and reload of ebook records is a fairly common occurrence, for all kinds of reasons. Also records are simply purged outright at times - for example, titles coming out of an aggregator package. So this is not an uncommon circumstance, and it is concerning if the records are hanging around for a long time.

**Comment by seanluyk** [comment] 2018-09-10 17:14
Is related to the larger issue of #932 that is high priority this term, so closing this issue as it's a duplicate

**Closed by seanluyk** 2018-09-10 17:14 UTC
