### ISSUE TITLE
record should be shadowed - LOST-ASSUM

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#890] opened 2016-01-22 20:48 UTC
https://www.library.ualberta.ca/catalog/7002744

This title has one item in a shadowed location: LOST-ASSUM. We should not see it in search results.

(via helpdesk ticket https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=32496)

**Comment by redlibrarian** [comment] 2016-02-05 20:34
Hmm. I don't know whether this is still coming through in Jim's data, or if my program isn't deleting records as expecting. Will have to investigate.

**Comment by theLinkResolver** [comment] 2016-02-11 18:13
@redlibrarian this record has all items in shadowed locations, but it's still showing up (sans items table). I think you're already on this, but I'm adding it as an example to help with followup:

https://www.library.ualberta.ca/catalog/2848879

**Comment by redlibrarian** [comment] 2016-03-07 17:49
I think this is a problem with deletions...

**Comment by redlibrarian** [comment] 2016-03-31 15:04
See #932

**Comment by redlibrarian** [comment] 2016-03-31 19:10
OK, with this one - the second example is gone (which is good). The first example is still present in the index, and when I look at it, it is *not* marked as deleted. This implies that the problem is with Jim's logic for how to handle shadowed records. What I think we should do is as follows: add a note to records with no holdings saying that the record may be missing or lost, and then in the summer we should sit down with Jim to make sure we know how all kinds of records are being handled/

**Comment by theLinkResolver** [comment] 2016-03-31 19:17
There's actually an interesting idea here (which I can't claim as my own) -- if we have a record where all items are in a shadowed location such as lost or missing, having the record in search results actually still helps the users discover the resource, and we can point them to ILL. Rather than not discovering the resource at all as is the case in the classic catalogue.

However, some shadowed locations do need to be suppressed completely, such as those with all items marked discard. Such records take a while to get purged (once a month).... unless we increase the frequency of this process (which I would say has some other benefits, too).

**Comment by redlibrarian** [comment] 2016-03-31 19:37
That's a good point. I can easily add a link to the ILL form when there are no holdings.

As you point out though, this isn't particularly simple, and we've been handling it on a pretty ad-hoc basis (both for Blacklight and EDS), so I'd like to get all the right people to sit down at some point to figure out what the best way is to handle all this.

**Comment by theLinkResolver** [comment] 2017-09-27 15:30
(cross-ref #813)

**Comment by redlibrarian** [comment] 2018-04-30 17:58
This is part of a larger shadowed/no holdings/deletes issue. Done when:

- [ ] Records with no unshadowed items are suppressed.

**Comment by seanluyk** [comment] 2018-09-10 15:54
@theLinkResolver could you please provide us with a fresh lost-assum item for testing purposes?

**Comment by theLinkResolver** [comment] 2018-09-10 16:51
@seanluyk There I don't currently see any records that should be shadowed entirely based on this location. There are records with LOST-ASSUM items but they have other legit visible items. I will have to revisit this.

**Comment by seanluyk** [comment] 2019-01-08 22:49
Closing as I can't find any examples, and usually, this sort of thing comes through to the helpdesk.

**Closed by seanluyk** 2019-01-08 22:49 UTC
Labels: Bib Records, bug
