### ISSUE TITLE
Article Search Null Results

### ISSUE THREAD

**Issue by kgood** [ualbertalib/discovery#546] opened 2015-10-01 14:06 UTC
Did this search - Learning to Die in the Anthropocene

Which resulted in zero articles being found in the articles pane of the bento.  Seems like it should have retrieved something based on some of those keywords.

**Comment by redlibrarian** [comment] 2015-10-07 16:37
This might be due to the fact that the article pane is limited to journal articles only...? I'll have to look into this.

**Comment by redlibrarian** [comment] 2015-10-14 17:33
Yes, the problem is that the bento pane is limited to journal articles. This search works: https://search.library.ualberta.ca/articles?q=Learning+to+Die+in+the+Anthropocene

So the question becomes related to our discussion point around bento panes (Issue #555 )

**Comment by redlibrarian** [comment] 2015-10-29 20:58
This will be fixed with the change in our bento panes.

**Closed by redlibrarian** 2015-10-29 20:58 UTC
Labels: For discussion
