### ISSUE TITLE
Looseleaf issue

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#596] opened 2015-10-07 21:01 UTC
Further to my issue with Hogg's Constitutional Law of Canada... I want the looseleaf.
Searching for "hogg constitutional law". Assuming I know to limit the search to "Continually Updated Resource" (CUR) (not sure that everyone will know what this means), I get 117 results... None of which are <i>Constitutional Law of Canada</i>. 
If I search for "constitutional law of canada hogg" and limit to CUR, there are 190 results. Still, not the actual item I'm looking for. Also, being that I've recently spent far too much time with the list of current law subscriptions, I have a feeling that the 190 results represents at least 80% of all the continually updated resources that actually exist in law.
The only way to find it was using the ISBN from NEOS. The result, https://search.library.ualberta.ca/catalog/2510419 seems to be labelled with the wrong format, which is why it doesn't appear in the list of CUR. Hopefully this is a one-off, but I worry that there are issues mapping format=looseleaf onto CUR?

**Comment by merisjames** [comment] 2015-10-07 21:08
More looseleafs that don't show as Continually Updated Resources 
https://search.library.ualberta.ca/catalog/82126 (admittedly, we don't subscribe to it any more).
https://search.library.ualberta.ca/catalog/2914687
https://search.library.ualberta.ca/catalog/384994 not a looseleaf, but is updated with pocket parts

**Comment by theLinkResolver** [comment] 2015-10-07 22:21
I can address this a bit more when I am back from holidays in a couple weeks.  The Continually Updated Resources format is a relatively new form of catalogue record, so in short, the new stuff is coded that way but the old stuff is just "Book".

**Comment by theLinkResolver** [comment] 2015-10-26 21:28
@merisjames I've been pondering this a bit more, and want to expand on my previous, brief answer.

"Integrating resource", as a bibliographic level in the cataloguing world, was implemented in 2002.  So, generally, any loose-leaf title that was catalogued prior to that was considered a monograph (displaying as "book").  Integrating resources are basically one of three things: a loose-leaf volume, an updating website, or an updating database; all three have the defining characteristic of the updates not remaining discrete*.

We borrowed the term that OCLC uses in its interface to describe these - "Continually updated resource", which is less-jargony than "Integrating resource", but still not super-clear to the user (and is technically not applicable once it ceases to be updated).  The problem is coming up with an user-friendly umbrella term that describes all three of loose-leafs, databases and websites.  Ugh!

That said, @redlibrarian and I are hopeful that we can figure out a way to combine more elements of the record to more precisely describe the format of something, in which case we might be able to use a term like "loose-leaf"... if it's a post-2002 record.  Which is not the case for this particular title......

As for your search, I did find the loose-leaf edition as result 15 in the search of "hogg constitutional law" without limiting to CUR. Not where we want it but it's there. If the edition ["4th ed. (looseleaf)"] was displayed in the search results, it would stick out a bit more, but that is adding another line and I'm not personally going to suggest that as an enhancement (although it may have merit, I'm undecided).

I'd like to investigate with Erika and @sjshores if there's anything we can do from a cataloguing perspective to improve the description of these loose-leaf titles.  I remember well a sad moment when a student, who was at the end of a major research project, complained to me that our Canadian legal treatises were all out of date... So she thought, because of the publication dates in the records (e.g. Alberta corporation manual, which began publishing in 1964, but is filed right up to present-day).

*I should note here: pocket part updates are discrete, and though the updates sometimes get integrated into reissue volumes, this is not always the case, so I think that's why they fall into the monograph category.

**Comment by theLinkResolver** [comment] 2015-10-30 15:21
I'm going to close this because we are going to address the mapping of formats elsewhere, and ensure that we get those labels right (issue #544). The issue of how loose-leafs are/were catalogued is not a Blacklight issue -- but like so many things, I'm glad it came up in this context.  I will bring the matter forward for further investigation.

**Closed by theLinkResolver** 2015-10-30 15:21 UTC
Labels: Data, Investigating, question
