### ISSUE TITLE
Splitting of 300 field and labeling 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#783] opened 2015-12-04 20:05 UTC
Not an urgent issue, but I was wondering if it may be worth reconsidering how the 300 field and subfields $a, $b, and $c are being split into multiple fields. It may be worth relabeling data from $b as something other than *description*, and $a as something other than *contains*, and possibly merging these fields (and $c) back onto one line.

Otherwise, we're getting lots of records that say stuff like, **Description**: ill, which isn't that meaningful to users I don't think. I know that this issue is solved in RDA - users won't think that the book is "ill"! 

When all 300 subfields appeared on one line in ISBD fashion, it still probably didn't make sense to users, but the other physical details didn't stand out quite as much as it came after the extent, and didn't get its own line.

I would recommend possibly putting the 300 subfields back together, and simply labeling this as **Contains**. For example, **Contains**: 1 vocal score (28 p.) ; 27 cm; **Contains**: 164 p. ill. 22 cm.

The only advantage I could see of ever splitting these is if we wanted users to be able to facet by extent, other physical details, or size. I'm not sure that we are. Is splitting the pagination into a separate field have something to do with how citations are generated? Maybe just pagination needs its own field?

**Comment by theLinkResolver** [comment] 2015-12-04 21:09
I agree on a couple of points. Currently, separating them gives them all equal prominence alongside other key identifiers like author and publisher. The data from 300 $b, labelled as Description, is particularly problematic in this way, as it may describe a characteristic of *part* of the work, rather than the whole work. For example, a novel like the Hobbit that contains maps:

https://search.library.ualberta.ca/catalog/1885588

I agree with the recommendation of bringing the 300 subfields together under a broader term. "Contains" might work, but that would need closer analysis across a variety of works and formats.

In the shorter term, to relabel this field, I think a suggestion is forthcoming from @sjshores who has been consulting about this problem with Brian Stearns and I.

**Comment by sjshores** [comment] 2015-12-04 21:12
Right, so here's Brian's response and recommendation:

Hi Sandra,

This actually is one aspect of Blacklight that I had noticed as being
likely to cause confusion for users.

If we insist on displaying each subelement of the physical description
element separately (like Scott, I think that this is not beneficial and
takes more display space--just as I think that the publication information
should remain as one element), likely the best label is that used for the
subfield, "Other physical details". This label is not very useful, but it
reflects the varied content that is recorded in this subfield, the context
of which depends on the type of material being catalogued (a book that
contains illustrations, a map that is coloured, a videorecording that is
black and white and has sound, a painting that is on wood, etc.)

According to R.D.A., the following elements can be recorded in this single
subfield: (a) sound content (in a resource not primarily recorded sound);
(b) illustrative content; (c) colour content; (d) sound characteristic; (e)
video characteristic; (f) production method; (g) layout; (h) base material;
(i) applied material; (j) mount; (k) reduction ratio; (l) polarity.

A label such as "Contains" or "Includes" is misleading because we have many
notes about content. "Characteristics" is misleading because, for example,
this novel does not have the characteristic of being a map.


I recommend bringing the 300 subfields together and using either Brian's
suggestion of Other Physical Details, or else just Other Details.

Sandra

**Comment by seanluyk** [comment] 2015-12-05 01:31
When cataloguing in RILM we separate pagination from physical description. Is physical description too librarianey? I like Other Details though.

**Comment by redlibrarian** [comment] 2015-12-07 16:53
As per @sjshores I'm going to relabel the Description field **Other Details** for now. Once this has been confirmed in production, let's move this issue to the January milestone to talk about the best way to combine those subfields.

**Comment by theLinkResolver** [comment] 2016-02-23 20:43
In addition to the most common 300 subfields a, b and c, there are other things in this field that should probably be considered for display (echoing some of the above sentiments). There are some not-so-nice results when we don't display them, e.g.:

https://www.library.ualberta.ca/catalog/796633

(The $e text "30 program files (BASIC) on 1 computer disk (5 1/4 in.)" is omitted - we just see the plus symbol in the size field, which comes right before $e)

**Comment by redlibrarian** [comment] 2016-04-12 17:00
As per this ticket, I have merged subfields a, b, c, and e into a single line. I used Brian's suggested label of "Other Physical Details" rather than "Contains", but that's easily changed. I can also add other subfields if anyone thinks they're necessary. When the next index is up, please take a look and let me know what you think of how the fields are displaying.

**Comment by theLinkResolver** [comment] 2016-04-12 17:05
@redlibrarian All of the subfields should display, really, as you will get partial data if any are omitted. e.g. $a5$fboxes$a(3$flinear ft.) would display as "5 (3" without $f!

The subfields for 300 are a, b, c, e, f, g, and 3. Thanks; I should have looked into this sooner.

**Comment by redlibrarian** [comment] 2016-04-12 17:28
OK. I've added the other subfields - take a look in the next release.

**Comment by theLinkResolver** [comment] 2016-04-21 17:19
Looks great! closing

**Closed by theLinkResolver** 2016-04-21 17:19 UTC
Labels: Check in Next-Release
